=== hypernumbers/hypernumbers/lib/hypernumbers-1.0/priv/rendering/xml/hypernumbers.dtd
<!-- The Hypernumbers DTD for the screen builder -->

<!-- all the elements have the same attributes so use an entity declaration -->
<!ENTITY % attributes "id ID #IMPLIED class NMTOKEN #IMPLIED">

<!-- renderer is the outline tag for the file -->
<!ELEMENT renderer (bindings, body)>

<!-- Defines the bindings of data sources to the id elments -->
<!-- the identity field maps to the id of the rendered html -->
<!ELEMENT bindings (binding)*>
<!ELEMENT binding EMPTY>
<!ATTLIST binding
          identity   IDREF                     #REQUIRED
          source     CDATA                     #REQUIRED
          rendertype (dynamic | static | both) "both"
>

<!-- Defines the html -->
<!ELEMENT body (div | span | table)*>
<!ELEMENT div (div | span | table)*>
<!ATTLIST div  %attributes; >
<!ELEMENT span (div | span | table)*>
<!ATTLIST span %attributes; >
<!ELEMENT table (tr)+>
<!ATTLIST table %attributes; >
<!ELEMENT tr (td)+>
<!ATTLIST tr %attributes; >
<!ELEMENT td (div | span | table)*>
<!ATTLIST td %attributes; >

=== hypernumbers/hypernumbers/lib/hypernumbers-1.0/priv/rendering/xml/example1.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE renderer SYSTEM "hypernumbers.dtd">
<renderer>
  <bindings>
    <binding identity="someid1" source="a1"    rendertype="static"/>
    <binding identity="someid2" source="b1"    rendertype="dynamic"/>
    <binding identity="someid3" source="a2"    rendertype="both"/>
    <binding identity="someid4" source="d3:d6" rendertype="both"/>
  </bindings>
  <body>
    <div id="someid1" class="classname1">
      <div>
        <span id="someid2" class = "classname2"></span>
        <span class="classname3"></span>
        <div id="someid3" class="classname4"></div>
        <div id="someid4"></div>
        <table>
          <tr><td></td></tr>
        </table>
      </div>
    </div>
  </body>
</renderer>
